@hostingURL= http://localhost:3000/api/

### Recuperar todos los vehiculos
GET {{hostingURL}}vehicle

### Recuperar vehiculo por id
GET {{hostingURL}}vehicle/CPS-519

###Crear un vehiculo
POST {{hostingURL}}vehicle
content-type: application/json

{
  "brand": "Renault",
  "model": "megane",
  "plate": "CPS-519",
  "userOwnerId": 1,
  "color": "Gris",
  "size": "small",
  "year": "2007-08-05T03:19:08.000Z",
  "available": true,
  "location": "Cra 45 # 6-98",
  "pricePerHour": 50000,
  "city": "Bogota"
}

###Actualizar un vehiculo por id
PUT {{hostingURL}}vehicle/1
content-type: application/json

{
  "brand": "Renault",
  "model": "megane",
  "plate": "ABC-222",
  "userOwnerId": 1,
  "color": "Gris",
  "size": "small",
  "year": "2007-08-05T03:19:08.000Z",
  "available": true,
  "location": "Cra 45 # 6-98",
  "pricePerHour": 50000,
  "city": "Bogota"
}

### Recuperar todos los usuarios
GET {{hostingURL}}user

### Recuperar usuario por id
GET {{hostingURL}}user/1

### Crear un usuario
POST {{hostingURL}}user
content-type: application/json

{
  "firstName": "Santiago",
  "lastName": "Rodriguez",
  "email": "santi@example1.com",
  "phoneNumber": "0987654321",
  "address": "Cra 78 # 12 - 34",
  "city": "Bogota",
  "role": "admin"
}

### Recuperar todos las rentas
GET {{hostingURL}}rental

### Recuperar historial de rentas de un usuario
GET {{hostingURL}}rental/1

### Recuperar historial de rentas de un vehiculo
GET {{hostingURL}}rental/vehicle/2

### Alquilar un vehiculo
POST {{hostingURL}}rental
content-type: application/json

{
  "startDate": "2023-08-27T14:00:00.000Z",
  "numHours": 5,
  "vehicleId": 2,
  "userId": 1
}
